2023-09-12 12:09:13 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: prepared statement "S_1" already exists
2023-09-12 12:09:13 [main] ERROR c.i.n.provider.DataCrawler - org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select c1_0."id" from "category" c1_0 where c1_0."slug"=? fetch first ? rows only] [ERROR: prepared statement "S_1" already exists] [n/a]; SQL [n/a]
2023-09-12 12:09:14 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: prepared statement "S_2" already exists
2023-09-12 12:09:14 [main] ERROR c.i.n.provider.DataCrawler - org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select a1_0."id" from "article" a1_0 where a1_0."slug"=? fetch first ? rows only] [ERROR: prepared statement "S_2" already exists] [n/a]; SQL [n/a]
2023-09-12 12:51:30 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: prepared statement "S_1" already exists
2023-09-12 12:51:30 [main] ERROR c.i.n.provider.DataCrawler - org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select c1_0."id" from "category" c1_0 where c1_0."slug"=? fetch first ? rows only] [ERROR: prepared statement "S_1" already exists] [n/a]; SQL [n/a]
2023-09-12 12:51:31 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: prepared statement "S_2" already exists
2023-09-12 12:51:31 [main] ERROR c.i.n.provider.DataCrawler - org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select a1_0."id" from "article" a1_0 where a1_0."slug"=? fetch first ? rows only] [ERROR: prepared statement "S_2" already exists] [n/a]; SQL [n/a]
